// main.rs
/* automatically generated by rust-bindgen 0.60.1 */

pub const FACTOR: ::std::os::raw::c_int = 2;
extern "C" {
    pub fn doubler(x: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}

fn main() {
    unsafe {
        println!("{}", doubler(1));
    }
}